import argparse
parser = argparse.ArgumentParser(prog = "drivebench", description = "Measure performance of a hard drive.", add_help = False)
parser.add_argument("-c", "--sequential-chunk-size", metavar = "MiB", type = int, default = 128, help = "For sequential reads, defines the chunk size in MiB. Defaults to %(default)d MiB.")
parser.add_argument("-S", "--sequential-samples", metavar = "count", type = int, default = 100, help = "For sequential reads, defines the number of data points to sample within the disk. Defaults to %(default)d.")
parser.add_argument("-t", "--thread-count", metavar = "count", type = int, default = 64, help = "For concurrent random access, defines the number of threads to use. Defaults to %(default)d.")
parser.add_argument("-r", "--read-counts-total", metavar = "count", type = int, default = 1280000, help = "For random access time measurements, defines the number of 4 kiB blocks to read total, divided evenly among threads. Defaults to %(default)d.")
parser.add_argument("-s", "--seed", metavar = "string", type = str, help = "Initializes the PRNG which creates the pseudo-random access pattern to this specific seed. Randomized by default. Can be any string.")
parser.add_argument("--read-4k-buckets", metavar = "count", type = int, default = 64, help = "Number of buckets to use for grouping 4k random reads. Defaults to %(default)d.")
parser.add_argument("--no-sequential", action = "store_true", help = "Do not measure sequential thread performance.")
parser.add_argument("--no-single-threaded-4k", action = "store_true", help = "Do not measure single-threaded 4k access latency.")
parser.add_argument("--no-multi-threaded-4k", action = "store_true", help = "Do not measure multi-threaded 4k access latency.")
parser.add_argument("-j", "--json-output", metavar = "filename", help = "Write results into this JSON file.")
parser.add_argument("-v", "--verbose", action = "count", default = 0, help = "Increase verbosity. Can be specified multiple times.")
parser.add_argument("device", metavar = "path", help = "Device of hard drive to benchmark.")
